# Generated by Django 6.0.6 on 2026-06-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_subtitle', models.TextField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('hero_button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('hero_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('promotional_banner_text', models.CharField(blank=True, max_length=255, null=True)),
                ('promotional_banner_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Homepage Content',
                'verbose_name_plural': 'Homepage Content',
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Old Money Algeria', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('tiktok_url', models.URLField(blank=True, null=True)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount above which delivery is free.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('home_delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bureau_delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('delivery_days', models.CharField(default='2-4 days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
