# Generated by Django 6.0.6 on 2026-06-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_pixel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
