# Generated by Django 6.0.6 on 2026-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_storesettings_google_analytics_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='lookbook/')),
                ('collection_slug', models.CharField(blank=True, help_text='Ex: chemises-premium', max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
