# Generated by Django 6.0.6 on 2026-06-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lookbookitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='collections_hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collections_hero_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
