# Generated by Django 6.0.6 on 2026-06-21 15:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homepagecontent_collections_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='collections_hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='lookbookitem',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
