# Generated by Django 6.0.6 on 2026-06-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepagecontent_collections_hero_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LookbookItem',
        ),
    ]
