# Generated by Django 6.0.6 on 2026-06-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_lookbookitem'),
        ('products', '0005_alter_collection_options_collection_display_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagecontent',
            name='collections_hero_image',
        ),
        migrations.RemoveField(
            model_name='homepagecontent',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collections_hero_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='HomepageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('NOUVEAUTES', 'Nouveautés'), ('BESTSELLERS', 'Bestsellers'), ('RECOMMANDATIONS', 'Recommandations'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
