# Generated by Django 6.0.6 on 2026-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_homepagecontent_collections_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='prop1_icon',
            field=models.CharField(choices=[('CROWN', 'Crown'), ('TRUCK', 'Truck'), ('DIAMOND', 'Diamond')], default='CROWN', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop1_text',
            field=models.TextField(default='Des matières nobles sélectionnées pour durer et affirmer votre statut.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop1_title',
            field=models.CharField(default='Qualité Premium', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop2_icon',
            field=models.CharField(choices=[('CROWN', 'Crown'), ('TRUCK', 'Truck'), ('DIAMOND', 'Diamond')], default='TRUCK', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop2_text',
            field=models.TextField(default='Payez en espèces à la livraison. Nous expédions partout en Algérie.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop2_title',
            field=models.CharField(default='Livraison 58 Wilayas', max_length=255),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop3_icon',
            field=models.CharField(choices=[('CROWN', 'Crown'), ('TRUCK', 'Truck'), ('DIAMOND', 'Diamond')], default='DIAMOND', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop3_text',
            field=models.TextField(default="Des coupes minimalistes inspirées par l'esthétique Old Money."),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='prop3_title',
            field=models.CharField(default='Élégance Intemporelle', max_length=255),
        ),
    ]
