# Generated by Django 6.0.6 on 2026-06-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_homepagecontent_prop1_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='active_theme',
            field=models.CharField(choices=[('dark-classique', 'Dark Classique'), ('green-luxury', 'Green Luxury'), ('forest-gold', 'Forest & Gold'), ('black-green', 'Black & Green'), ('gold-dark', 'Gold & Dark'), ('pure-green', 'Pure Green'), ('custom', 'Custom Theme')], default='dark-classique', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='custom_accent_color',
            field=models.CharField(blank=True, help_text='e.g. #D4AF37', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='custom_bg_color',
            field=models.CharField(blank=True, help_text='e.g. #0A0A0A', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='custom_cards_color',
            field=models.CharField(blank=True, help_text='e.g. #111111', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='custom_primary_color',
            field=models.CharField(blank=True, help_text='e.g. #1B5E20', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='custom_text_color',
            field=models.CharField(blank=True, help_text='e.g. #FFFFFF', max_length=7, null=True),
        ),
    ]
