# Generated by Django 6.0.6 on 2026-06-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_storesettings_active_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='enable_whatsapp_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notification_phone',
            field=models.CharField(blank=True, help_text='e.g. +213XXXXXXXXX', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_apikey',
            field=models.CharField(blank=True, help_text='CallMeBot API key', max_length=100, null=True),
        ),
    ]
