# Generated by Django 6.0.6 on 2026-06-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='guest_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='guest_phone',
        ),
    ]
