# Generated by Django 6.0.6 on 2026-06-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_collection_image_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'id']},
        ),
    ]
